//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phasmo_helper.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DescriptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("phasmo_helper.Resources.DescriptionResources", typeof(DescriptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В мультиплеере выбирает себе одну конкретную жертву. При атаке ориентируется только на рассудок выбранной жертвы, а не на общий. Постоянно ходит за жертвой. В одиночной игре или если цель вышла из дома, работает как обычный призрак. Через Направленный Микрофон можно услышать особый крик..
        /// </summary>
        internal static string Description_Banshee {
            get {
                return ResourceManager.GetString("Description_Banshee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Охотится чаще, чем другие призраки и может начать охоту независимо от уровня рассудка. Радиус работы распятия увеличен..
        /// </summary>
        internal static string Description_Demon {
            get {
                return ResourceManager.GetString("Description_Demon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Может охотиться от 40% рассудка и ниже. От него невозможно спрятаться. Он очень быстр, когда не видит цель, но подходя ближе становится медленным настолько, что от него можно уйти пешком. Имеет особый звук ответа через радиоприёмник..
        /// </summary>
        internal static string Description_Deogen {
            get {
                return ResourceManager.GetString("Description_Deogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень редко меняет свою комнату (практически никогда). Его Лазерный Проектор видим только на камерах + он его не покажет, если с камерой находиться в его комнате..
        /// </summary>
        internal static string Description_Goryo {
            get {
                return ResourceManager.GetString("Description_Goryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На холоде ходит быстрее, в прогретых частях дома - медленнее. Также на холоде можно увидеть морозное дыхание у этого призрака (такое же как у игрока)..
        /// </summary>
        internal static string Description_Hantu {
            get {
                return ResourceManager.GetString("Description_Hantu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Когда генератор включен, он сильно повышает скорость, когда его цель далеко. На более близком расстоянии скорость уменьшается. Если генератор отключен - поведение стандартного призрака..
        /// </summary>
        internal static string Description_Jinn {
            get {
                return ResourceManager.GetString("Description_Jinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Любит темноту. Атакует при 60% рассудка, когда свет в комнате выключен. При 40%, когда включен..
        /// </summary>
        internal static string Description_Mare {
            get {
                return ResourceManager.GetString("Description_Mare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Много рассудка - медленный, мало рассудка - очень быстрый. Ускоряться начинает от 45% рассудка и ниже. При ответе через радиоприёмник или при разговоре через направленный миркрофон может наслать на игрока проклятие, что приведёт к стремительному снижению рассудка..
        /// </summary>
        internal static string Description_Moroi {
            get {
                return ResourceManager.GetString("Description_Moroi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень тихо ходит. Более часто издаёт паранормальные звуки в Направленном Микрофоне..
        /// </summary>
        internal static string Description_Myling {
            get {
                return ResourceManager.GetString("Description_Myling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имеет шанс в 25% не оставить отпечатки. Также имеет особый шестипалый отпечаток руки..
        /// </summary>
        internal static string Description_Obake {
            get {
                return ResourceManager.GetString("Description_Obake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очень активен. Во время охоты почти не исчезает. Не может сделать шаровой ивент..
        /// </summary>
        internal static string Description_Oni {
            get {
                return ResourceManager.GetString("Description_Oni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Может начать охоту при рассудке 60% и ниже. Но также атакует при любом уровне рассудка, если задует 3 свечи..
        /// </summary>
        internal static string Description_Onryo {
            get {
                return ResourceManager.GetString("Description_Onryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если на него смотреть, рассудок понжается быстрее. Он исчезает с фотографий, но делает это не прерывая звук ивента..
        /// </summary>
        internal static string Description_Phantom {
            get {
                return ResourceManager.GetString("Description_Phantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Он очень много взаимодействует. Кидает много предметов и порой на большие расстояния, часто дёргает двери. Бесполезен в пустых комнатах..
        /// </summary>
        internal static string Description_Poltergeist {
            get {
                return ResourceManager.GetString("Description_Poltergeist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Может начать охоту от 65% рассудка, если рядом включена электроника (только оборудование игроков, свет в доме или находящаяся в нём электроника не считается). От этой электроники он питается и увеличивает скорость. Увеличен радиус чувствительности к электронике игрока..
        /// </summary>
        internal static string Description_Raiju {
            get {
                return ResourceManager.GetString("Description_Raiju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Он очень медленный, когда не видит игрока. Когда видит - очень быстрый..
        /// </summary>
        internal static string Description_Revenant {
            get {
                return ResourceManager.GetString("Description_Revenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стесняшка. Может охотиться от 35% рассудка и ниже, но не начинает охоту, когда кто-то находится в его комнате..
        /// </summary>
        internal static string Description_Shade {
            get {
                return ResourceManager.GetString("Description_Shade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если его заблаговонять, то он не cможет охотиться 3 минуты..
        /// </summary>
        internal static string Description_Spirit {
            get {
                return ResourceManager.GetString("Description_Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Может начать озотиться от 75% рассудка, но в течение игры стареет. В конце концов может начать охоту только после достижения отметки ниже 15% рассудка..
        /// </summary>
        internal static string Description_Thaye {
            get {
                return ResourceManager.GetString("Description_Thaye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полностью копирует поведение других призраков. Имеет Призрачный Огонёк, который считается у него не уликой, а абилкой..
        /// </summary>
        internal static string Description_TheMimic {
            get {
                return ResourceManager.GetString("Description_TheMimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Их буквально двое. Один из них медленнее, чем другие призраки, другой - быстрее. Могут взаимодействовать с разными предметами (порой и в разных комнатах) одновременно..
        /// </summary>
        internal static string Description_TheTwins {
            get {
                return ResourceManager.GetString("Description_TheTwins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Может телепортироваться к игрогу через весь дом, а затем вернуться к себе в комнату (не путать с телепортацией ивентом, неподалеку от своей комнаты). Он никогда не наступит в соль..
        /// </summary>
        internal static string Description_Wraith {
            get {
                return ResourceManager.GetString("Description_Wraith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Может начать охоту от 80% рассудка, если болтать с ним рядом. Во время охоты глух, глуп и слеп - уменьшен радиус чувствивтельности к электронике/звукам игрока..
        /// </summary>
        internal static string Description_Yokai {
            get {
                return ResourceManager.GetString("Description_Yokai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При ивентах он очень сильно сажает рассудок. Если заблаговонять, то временно перестанет слоняться по дому..
        /// </summary>
        internal static string Description_Yurei {
            get {
                return ResourceManager.GetString("Description_Yurei", resourceCulture);
            }
        }
    }
}
