//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phasmo_helper.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GhostResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GhostResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("phasmo_helper.Resources.GhostResources", typeof(GhostResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Банши.
        /// </summary>
        internal static string GhostName_Banshee {
            get {
                return ResourceManager.GetString("GhostName_Banshee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Демон.
        /// </summary>
        internal static string GhostName_Demon {
            get {
                return ResourceManager.GetString("GhostName_Demon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деоген.
        /// </summary>
        internal static string GhostName_Deogen {
            get {
                return ResourceManager.GetString("GhostName_Deogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Горё.
        /// </summary>
        internal static string GhostName_Goryo {
            get {
                return ResourceManager.GetString("GhostName_Goryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ханту.
        /// </summary>
        internal static string GhostName_Hantu {
            get {
                return ResourceManager.GetString("GhostName_Hantu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Джинн.
        /// </summary>
        internal static string GhostName_Jinn {
            get {
                return ResourceManager.GetString("GhostName_Jinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мара.
        /// </summary>
        internal static string GhostName_Mare {
            get {
                return ResourceManager.GetString("GhostName_Mare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морой.
        /// </summary>
        internal static string GhostName_Moroi {
            get {
                return ResourceManager.GetString("GhostName_Moroi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мюллинг.
        /// </summary>
        internal static string GhostName_Myling {
            get {
                return ResourceManager.GetString("GhostName_Myling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обаке.
        /// </summary>
        internal static string GhostName_Obake {
            get {
                return ResourceManager.GetString("GhostName_Obake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Они.
        /// </summary>
        internal static string GhostName_Oni {
            get {
                return ResourceManager.GetString("GhostName_Oni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Онрё.
        /// </summary>
        internal static string GhostName_Onryo {
            get {
                return ResourceManager.GetString("GhostName_Onryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фантом.
        /// </summary>
        internal static string GhostName_Phantom {
            get {
                return ResourceManager.GetString("GhostName_Phantom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полтергейст.
        /// </summary>
        internal static string GhostName_Poltergeist {
            get {
                return ResourceManager.GetString("GhostName_Poltergeist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раидзю.
        /// </summary>
        internal static string GhostName_Raiju {
            get {
                return ResourceManager.GetString("GhostName_Raiju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ревенант.
        /// </summary>
        internal static string GhostName_Revenant {
            get {
                return ResourceManager.GetString("GhostName_Revenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тень.
        /// </summary>
        internal static string GhostName_Shade {
            get {
                return ResourceManager.GetString("GhostName_Shade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дух.
        /// </summary>
        internal static string GhostName_Spirit {
            get {
                return ResourceManager.GetString("GhostName_Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тайэ.
        /// </summary>
        internal static string GhostName_Thaye {
            get {
                return ResourceManager.GetString("GhostName_Thaye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мимик.
        /// </summary>
        internal static string GhostName_TheMimic {
            get {
                return ResourceManager.GetString("GhostName_TheMimic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Близнецы.
        /// </summary>
        internal static string GhostName_TheTwins {
            get {
                return ResourceManager.GetString("GhostName_TheTwins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мираж.
        /// </summary>
        internal static string GhostName_Wraith {
            get {
                return ResourceManager.GetString("GhostName_Wraith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ёкай.
        /// </summary>
        internal static string GhostName_Yokai {
            get {
                return ResourceManager.GetString("GhostName_Yokai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юрей.
        /// </summary>
        internal static string GhostName_Yurei {
            get {
                return ResourceManager.GetString("GhostName_Yurei", resourceCulture);
            }
        }
    }
}
